# Generated by Django 2.0.2 on 2018-02-15 18:35

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('website', '0001_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='post_title')),
                ('body', models.TextField(verbose_name='post_body')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='post_create_time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='post_update_time')),
                ('tags', taggit.managers.TaggableManager(help_text='post_tags_help_text', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='post_tags')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
    ]
