# Generated by Django 2.0.2 on 2018-02-15 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='announcement_title')),
                ('body', models.TextField(verbose_name='announcement_body')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='announcement_create_time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='announcement_update_time')),
            ],
            options={
                'verbose_name': 'announcement',
                'verbose_name_plural': 'announcements',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.Post')),
                ('start_time', models.DateTimeField(verbose_name='event_start_time')),
                ('end_time', models.DateTimeField(verbose_name='event_end_time')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
            bases=('website.post',),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='registration_submit_time')),
            ],
            options={
                'verbose_name': 'registration',
                'verbose_name_plural': 'registrations',
            },
        ),
        migrations.CreateModel(
            name='VideoContestGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='video_contest_group_name')),
            ],
            options={
                'verbose_name': 'video_contest_group',
                'verbose_name_plural': 'video_contest_groups',
            },
        ),
        migrations.CreateModel(
            name='VideoContestWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.CharField(max_length=100, verbose_name='video_contest_winner_prize')),
            ],
            options={
                'verbose_name': 'video_contest_winner',
                'verbose_name_plural': 'video_contest_winners',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.Event')),
                ('venue', models.CharField(max_length=100, verbose_name='salon_venue')),
                ('address', models.CharField(max_length=100, verbose_name='salon_address')),
                ('door_time', models.DateTimeField(verbose_name='salon_door_time')),
            ],
            options={
                'verbose_name': 'salon',
                'verbose_name_plural': 'salons',
            },
            bases=('website.event',),
        ),
        migrations.CreateModel(
            name='SalonRegistration',
            fields=[
                ('registration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.Registration')),
            ],
            options={
                'verbose_name': 'salon_registration',
                'verbose_name_plural': 'salon_registrations',
            },
            bases=('website.registration',),
        ),
        migrations.CreateModel(
            name='VideoContest',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.Event')),
            ],
            options={
                'verbose_name': 'video_contest',
                'verbose_name_plural': 'video_contests',
            },
            bases=('website.event',),
        ),
        migrations.CreateModel(
            name='VideoContestRegistration',
            fields=[
                ('registration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.Registration')),
                ('youtube_url', embed_video.fields.EmbedVideoField(verbose_name='video_contest_registration_youtube_url')),
                ('introduction', models.TextField(verbose_name='video_contest_registration_introduction')),
                ('phone_number', models.CharField(max_length=20, verbose_name='video_contest_registration_phone_number')),
                ('address', models.CharField(max_length=100, verbose_name='video_contest_registration_address')),
                ('email', models.CharField(max_length=100, verbose_name='video_contest_registration_email')),
                ('questions', models.TextField(blank=True, verbose_name='video_contest_registration_questions')),
                ('qualified', models.BooleanField(default=False, verbose_name='video_contest_registration_qualified')),
            ],
            options={
                'verbose_name': 'video_contest_registration',
                'verbose_name_plural': 'video_contest_registrations',
            },
            bases=('website.registration',),
        ),
        migrations.AddField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Event', verbose_name='event'),
        ),
        migrations.AddField(
            model_name='registration',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='registration_submitter'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Event', verbose_name='event'),
        ),
        migrations.AddField(
            model_name='videocontestwinner',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.VideoContestRegistration', verbose_name='video_contest_winner_registration'),
        ),
        migrations.AddField(
            model_name='videocontestwinner',
            name='video_contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.VideoContest', verbose_name='video_contest'),
        ),
        migrations.AddField(
            model_name='videocontestgroup',
            name='video_contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.VideoContest', verbose_name='video_contest'),
        ),
        migrations.AlterUniqueTogether(
            name='videocontestwinner',
            unique_together={('video_contest', 'registration')},
        ),
        migrations.AlterUniqueTogether(
            name='videocontestgroup',
            unique_together={('video_contest', 'name')},
        ),
    ]
