# Generated by Django 2.0.2 on 2018-02-16 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_event_announcement_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocontestregistration',
            name='contestant_name',
            field=models.CharField(default='', max_length=100, verbose_name='video_contest_registration_contestant_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocontestregistration',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.VideoContestGroup', verbose_name='video_contest_registration_group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocontestregistration',
            name='video_title',
            field=models.CharField(default='', max_length=100, verbose_name='video_contest_registration_video_title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videocontestregistration',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='video_contest_registration_email'),
        ),
    ]
