# Generated by Django 2.0.2 on 2018-02-17 18:45

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_video_contest_registration_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocontestregistration',
            name='youtube_url',
            field=embed_video.fields.EmbedVideoField(unique=True, verbose_name='video_contest_registration_youtube_url'),
        ),
    ]
