# Generated by Django 2.0.2 on 2018-02-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_video_contest_registration_youtube_url_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='voted_videos',
            field=models.ManyToManyField(related_name='_profile_voted_videos_+', to='website.VideoContestRegistration'),
        ),
        migrations.AddField(
            model_name='videocontestregistration',
            name='votes',
            field=models.PositiveIntegerField(default=0, verbose_name='video_contest_registration_votes'),
        ),
    ]
