# Generated by Django 2.0.2 on 2018-02-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_video_contest_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='voted_videos',
            field=models.ManyToManyField(related_name='voters', to='website.VideoContestRegistration'),
        ),
    ]
