# Generated by Django 2.0.2 on 2018-02-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_video_contest_registration_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocontestregistration',
            name='video_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='video_contest_registration_video_number'),
        ),
    ]
