# Generated by Django 2.0.2 on 2018-02-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_video_contest_registration_video_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='voted_videos',
            field=models.ManyToManyField(blank=True, related_name='voters', to='website.VideoContestRegistration'),
        ),
    ]
