# Generated by Django 2.0.2 on 2018-02-22 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_profile_voted_videos_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='event_registration_end_time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='registration_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='event_registration_start_time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocontest',
            name='voting_end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='video_contest_voting_end_time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocontest',
            name='voting_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='video_contest_voting_start_time'),
            preserve_default=False,
        ),
    ]
