# Generated by Django 2.0.2 on 2018-02-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_user_proxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
    ]
