# Generated by Django 2.0.2 on 2018-02-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_profile_verbose_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'privacy_policy_verbose_name',
            },
        ),
    ]
