# Generated by Django 2.0.2 on 2018-05-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_privacy_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'home_tab',
                'verbose_name_plural': 'home_tabs',
            },
        ),
    ]
