# Generated by Django 2.0.2 on 2018-05-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_salon_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='registered_salons',
        ),
    ]
