# Generated by Django 2.0.2 on 2018-05-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_profile_remove_registered_salons'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocontestwinner',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
