# Generated by Django 3.2.3 on 2021-05-23 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_salon_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='max_attendance_per_registration',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=1)]),
        ),
        migrations.AddField(
            model_name='salonregistration',
            name='other_attendees_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salonregistration',
            name='attendance',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=1)]),
        ),
    ]
