from website.admins.headline_admin import HeadlineAdmin
from website.admins.home_tab import HomeTabAdmin
from website.admins.post_admin import PostAdmin
from website.admins.salon_admin import SalonAdmin
from website.admins.salon_registration_admin import SalonRegistrationAdmin
from website.admins.user_profile_admin import UserProfileAdmin
from website.admins.video_contest_admin import VideoContestAdmin
from website.admins.video_contest_registration_admin import VideoContestRegistrationAdmin
